package clasesBean;
// Generated 24-abr-2018 8:35:34 by Hibernate Tools 5.2.3.Final

/**
 * Alumnosasignaturas generated by hbm2java
 */
public class Alumnosasignaturas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idAlumnosAsignaturas;
	private Alumnos alumno;
	private Asignaturas asignatura;

	public Alumnosasignaturas() {
	}

	public Alumnosasignaturas(int idAlumnosAsignaturas, Alumnos alumno, Asignaturas asignatura) {
		this.idAlumnosAsignaturas = idAlumnosAsignaturas;
		this.alumno = alumno;
		this.asignatura = asignatura;
	}

	public int getIdAlumnosAsignaturas() {
		return this.idAlumnosAsignaturas;
	}

	public void setIdAlumnosAsignaturas(int idAlumnosAsignaturas) {
		this.idAlumnosAsignaturas = idAlumnosAsignaturas;
	}

	public Alumnos getAlumno() {
		return alumno;
	}

	public void setAlumno(Alumnos alumno) {
		this.alumno = alumno;
	}

	public Asignaturas getAsignatura() {
		return asignatura;
	}

	public void setAsignatura(Asignaturas asignatura) {
		this.asignatura = asignatura;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	

}
