package clasesBean;
// Generated 24-abr-2018 8:35:34 by Hibernate Tools 5.2.3.Final

import java.util.Set;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idAlumno;
	private Usuarios usuario;
	private Set <Alumnosprofesores> alumnosprofesores;
	private Set <Alumnosasignaturas> alumnosasignaturas;
	private Set <Testalumno> testalumnos;

	public Alumnos() {
	}

	public Alumnos(Usuarios usuario) {
		this.usuario = usuario;
	}
	public Alumnos(int idAlumno, Usuarios usuario) {
		this.idAlumno = idAlumno;
		this.usuario = usuario;
	}
	public int getIdAlumno() {
		return this.idAlumno;
	}

	public void setIdAlumno(int idAlumno) {
		this.idAlumno = idAlumno;
	}

	public Usuarios getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuarios usuario) {
		this.usuario = usuario;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public Set<Alumnosprofesores> getAlumnosprofesores() {
		return alumnosprofesores;
	}

	public void setAlumnosprofesores(Set<Alumnosprofesores> alumnosprofesores) {
		this.alumnosprofesores = alumnosprofesores;
	}

	public Set <Alumnosasignaturas> getAlumnosasignaturas() {
		return alumnosasignaturas;
	}

	public void setAlumnosasignaturas(Set <Alumnosasignaturas> alumnosasignaturas) {
		this.alumnosasignaturas = alumnosasignaturas;
	}

	public Set <Testalumno> getTestalumnos() {
		return testalumnos;
	}

	public void setTestalumnos(Set <Testalumno> testalumnos) {
		this.testalumnos = testalumnos;
	}


}
