package clasesBean;
// Generated 24-abr-2018 8:35:34 by Hibernate Tools 5.2.3.Final

/**
 * Alumnosprofesores generated by hbm2java
 */
public class Alumnosprofesores implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idAlumnosProfesores;
	private Profesores profesor;
	private Alumnos alumno;

	public Alumnosprofesores() {
	}

	public Alumnosprofesores(int idAlumnosProfesores, Alumnos alumno, Profesores profesor) {
		this.idAlumnosProfesores = idAlumnosProfesores;
		this.profesor = profesor;
		this.alumno = alumno;
	}
	public Alumnosprofesores(Alumnos alumno, Profesores profesor) {
		this.profesor = profesor;
		this.alumno = alumno;
	}

	public int getIdAlumnosProfesores() {
		return this.idAlumnosProfesores;
	}

	public void setIdAlumnosProfesores(int idAlumnosProfesores) {
		this.idAlumnosProfesores = idAlumnosProfesores;
	}

	public Profesores getProfesor() {
		return profesor;
	}

	public void setProfesor(Profesores profesor) {
		this.profesor = profesor;
	}

	public Alumnos getAlumno() {
		return alumno;
	}

	public void setAlumno(Alumnos alumno) {
		this.alumno = alumno;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	

}
