package clasesBean;
// Generated 24-abr-2018 8:35:34 by Hibernate Tools 5.2.3.Final

import java.util.Set;

/**
 * Asignaturas generated by hbm2java
 */
public class Asignaturas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idAsignatura;
	private String nombreAsignatura;
	private Set <Alumnosasignaturas> alumnosasignaturas;
	private Set <Profesoresasignaturas> profesoresasignaturas;
	private Set <Temas> temas;

	public Asignaturas() {
	}

	public Asignaturas(int idAsignatura, String nombreAsignatura) {
		this.idAsignatura = idAsignatura;
		this.nombreAsignatura = nombreAsignatura;
	}

	public int getIdAsignatura() {
		return this.idAsignatura;
	}

	public void setIdAsignatura(int idAsignatura) {
		this.idAsignatura = idAsignatura;
	}

	public String getNombreAsignatura() {
		return this.nombreAsignatura;
	}

	public void setNombreAsignatura(String nombreAsignatura) {
		this.nombreAsignatura = nombreAsignatura;
	}

	public Set <Alumnosasignaturas> getAlumnosasignaturas() {
		return alumnosasignaturas;
	}

	public void setAlumnosasignaturas(Set <Alumnosasignaturas> alumnosasignaturas) {
		this.alumnosasignaturas = alumnosasignaturas;
	}

	public Set <Profesoresasignaturas> getProfesoresasignaturas() {
		return profesoresasignaturas;
	}

	public void setProfesoresasignaturas(Set <Profesoresasignaturas> profesoresasignaturas) {
		this.profesoresasignaturas = profesoresasignaturas;
	}

	public Set <Temas> getTemas() {
		return temas;
	}

	public void setTemas(Set <Temas> temas) {
		this.temas = temas;
	}

}
