package clasesBean;
// Generated 24-abr-2018 8:35:34 by Hibernate Tools 5.2.3.Final

import java.util.Set;

/**
 * Profesores generated by hbm2java
 */
public class Profesores implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idProfesor;
	private Usuarios usuario;
	private Set <Alumnosprofesores> alumnosprofesores;
	private Set <Profesoresasignaturas> profesoresasignaturas;
	private Set <Test> tests;

	public Profesores() {
	}

	public Profesores(int idProfesor, Usuarios usuario) {
		this.idProfesor = idProfesor;
		this.usuario = usuario;
	}

	public Profesores(Usuarios usuario) {
		this.usuario = usuario;
	}
	public int getIdProfesor() {
		return this.idProfesor;
	}

	public void setIdProfesor(int idProfesor) {
		this.idProfesor = idProfesor;
	}

	public Usuarios getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuarios usuario) {
		this.usuario = usuario;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	public Set<Alumnosprofesores> getAlumnosprofesores() {
		return alumnosprofesores;
	}

	public void setAlumnosprofesores(Set<Alumnosprofesores> alumnosprofesores) {
		this.alumnosprofesores = alumnosprofesores;
	}

	public Set <Profesoresasignaturas> getProfesoresasignaturas() {
		return profesoresasignaturas;
	}

	public void setProfesoresasignaturas(Set <Profesoresasignaturas> profesoresasignaturas) {
		this.profesoresasignaturas = profesoresasignaturas;
	}

	public Set <Test> getTests() {
		return tests;
	}

	public void setTests(Set <Test> tests) {
		this.tests = tests;
	}
	

}
