package clasesBean;
// Generated 24-abr-2018 8:35:34 by Hibernate Tools 5.2.3.Final

/**
 * Profesoresasignaturas generated by hbm2java
 */
public class Profesoresasignaturas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idProfesoresAsignaturas;
	private Profesores profesor;
	private Asignaturas asignatura;

	public Profesoresasignaturas() {
	}

	public Profesoresasignaturas(int idProfesoresAsignaturas, Profesores profesor, Asignaturas asignatura) {
		this.idProfesoresAsignaturas = idProfesoresAsignaturas;
		this.profesor = profesor;
		this.asignatura = asignatura;
	}

	public int getIdProfesoresAsignaturas() {
		return this.idProfesoresAsignaturas;
	}

	public void setIdProfesoresAsignaturas(int idProfesoresAsignaturas) {
		this.idProfesoresAsignaturas = idProfesoresAsignaturas;
	}

	public Profesores getProfesor() {
		return profesor;
	}

	public void setProfesor(Profesores profesor) {
		this.profesor = profesor;
	}

	public Asignaturas getAsignatura() {
		return asignatura;
	}

	public void setAsignatura(Asignaturas asignatura) {
		this.asignatura = asignatura;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}


	

}
