package clasesBean;
// Generated 24-abr-2018 8:35:34 by Hibernate Tools 5.2.3.Final

/**
 * Respuestas generated by hbm2java
 */
public class Respuestas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idRespuesta;
	private String descRespuesta;
	private Boolean escorrectaRespuesta;
	private Preguntas pregunta;

	public Respuestas() {
	}

	public Respuestas(int idRespuesta, String descRespuesta, Preguntas pregunta) {
		this.idRespuesta = idRespuesta;
		this.descRespuesta = descRespuesta;
		this.pregunta = pregunta;
	}

	public Respuestas(int idRespuesta, String descRespuesta, Boolean escorrectaRespuesta, Preguntas pregunta) {
		this.idRespuesta = idRespuesta;
		this.descRespuesta = descRespuesta;
		this.escorrectaRespuesta = escorrectaRespuesta;
		this.pregunta = pregunta;
	}

	public int getIdRespuesta() {
		return this.idRespuesta;
	}

	public void setIdRespuesta(int idRespuesta) {
		this.idRespuesta = idRespuesta;
	}

	public String getDescRespuesta() {
		return this.descRespuesta;
	}

	public void setDescRespuesta(String descRespuesta) {
		this.descRespuesta = descRespuesta;
	}

	public Boolean getEscorrectaRespuesta() {
		return this.escorrectaRespuesta;
	}

	public void setEscorrectaRespuesta(Boolean escorrectaRespuesta) {
		this.escorrectaRespuesta = escorrectaRespuesta;
	}

	public Preguntas getPregunta() {
		return pregunta;
	}

	public void setPregunta(Preguntas pregunta) {
		this.pregunta = pregunta;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}



}
