package clasesBean;
// Generated 24-abr-2018 8:35:34 by Hibernate Tools 5.2.3.Final

import java.util.Set;

/**
 * Temas generated by hbm2java
 */
public class Temas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idTema;
	private String nombreTema;
	private Asignaturas asignatura;
	private Set <Test> tests;

	public Temas() {
	}

	public Temas(int idTema, String nombreTema, Asignaturas asignatura) {
		this.idTema = idTema;
		this.nombreTema = nombreTema;
		this.asignatura = asignatura;
	}

	public int getIdTema() {
		return this.idTema;
	}

	public void setIdTema(int idTema) {
		this.idTema = idTema;
	}

	public String getNombreTema() {
		return this.nombreTema;
	}

	public void setNombreTema(String nombreTema) {
		this.nombreTema = nombreTema;
	}

	public Asignaturas getAsignatura() {
		return asignatura;
	}

	public void setAsignatura(Asignaturas asignatura) {
		this.asignatura = asignatura;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public Set <Test> getTests() {
		return tests;
	}

	public void setTests(Set <Test> tests) {
		this.tests = tests;
	}

	
}
