package clasesBean;
// Generated 24-abr-2018 8:35:34 by Hibernate Tools 5.2.3.Final

/**
 * Testalumno generated by hbm2java
 */
public class Testalumno implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idTestAlumno;
	private Alumnos alumno;
	private Test test;
	private long puntuacionTest;

	public Testalumno() {
	}

	public Testalumno(int idTestAlumno, Alumnos alumno, Test test, long puntuacionTest) {
		this.idTestAlumno = idTestAlumno;
		this.alumno = alumno;
		this.test = test;
		this.puntuacionTest = puntuacionTest;
	}

	public int getIdTestAlumno() {
		return this.idTestAlumno;
	}

	public void setIdTestAlumno(int idTestAlumno) {
		this.idTestAlumno = idTestAlumno;
	}


	public Alumnos getAlumno() {
		return alumno;
	}

	public void setAlumno(Alumnos alumno) {
		this.alumno = alumno;
	}

	public Test getTest() {
		return test;
	}

	public void setTest(Test test) {
		this.test = test;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public long getPuntuacionTest() {
		return this.puntuacionTest;
	}

	public void setPuntuacionTest(long puntuacionTest) {
		this.puntuacionTest = puntuacionTest;
	}

}
