package clasesBean;
// Generated 24-abr-2018 8:35:34 by Hibernate Tools 5.2.3.Final

import java.util.Set;

/**
 * Tipopregunta generated by hbm2java
 */
public class Tipopregunta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idTipoPregunta;
	private String nombreTipoPregunta;
	private Set <Preguntas> preguntas;

	public Tipopregunta() {
	}

	public Tipopregunta(int idTipoPregunta, String nombreTipoPregunta) {
		this.idTipoPregunta = idTipoPregunta;
		this.nombreTipoPregunta = nombreTipoPregunta;
	}

	public int getIdTipoPregunta() {
		return this.idTipoPregunta;
	}

	public void setIdTipoPregunta(int idTipoPregunta) {
		this.idTipoPregunta = idTipoPregunta;
	}

	public String getNombreTipoPregunta() {
		return this.nombreTipoPregunta;
	}

	public void setNombreTipoPregunta(String nombreTipoPregunta) {
		this.nombreTipoPregunta = nombreTipoPregunta;
	}

	public Set<Preguntas> getPreguntas() {
		return preguntas;
	}

	public void setPreguntas(Set<Preguntas> preguntas) {
		this.preguntas = preguntas;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	

}
